### ISSUE TITLE
Compatibility with linuxbrew

### ISSUE THREAD

**Issue by srijanshetty** [laurent22/homebrew-massren#3]
I couldn't install massren via linuxbrew. Is it incompatible with it, if so, do you want me to take a shot at it?

**Comment by laurent22** [comment]
I'm not familiar with Linuxbrew, but if you can make it compatible then yes please feel free to give it a try. I'd be glad to merge the changes.

**Comment by srijanshetty** [comment]
Hey @laurent22, I was able to use brew tap and install massren using linuxbrew like it's MacOS counterpart homebrew without any changes!

You can go ahead and close this issue.

**Comment by laurent22** [comment]
Thanks, good to know it's compatible with Linuxbrew, I've mentioned it in the readme file.
